### ISSUE TITLE
Aggiungere il campo profilePic alla response di User/GetUserData

### ISSUE THREAD

**Issue by yassindeb** [SimoneMonzardo/easyNet#120]
### Descrizione

Per la pagina utente dell'url dell'imagine del profilo
![image](https://github.com/SimoneMonzardo/easyNet/assets/79911341/9fe1e53b-effa-435c-b603-cadfd36daa9c)

### Passi per riprodurre il bug

1. Aggiungere il campo profilePic

### Area del progetto

API

**Comment by furlangabriele** [comment]
fatto
