### ISSUE TITLE
Component: User Profile Header

### ISSUE THREAD

**Issue by Ferrario-Filippo** [SimoneMonzardo/easyNet#24]
Create this component:
![Screenshot 2023-05-23 095441](https://github.com/SimoneMonzardo/easyNet/assets/91730716/d7415b65-585a-4724-b8c0-3b1508a44f31)

Requirements:
- Followers count should be passed as a parameter
- Following count should be passed as a parameter
- User name should be passed as a parameter
- Description should be passed as a parameter
- Profile picture should be passed as a parameter
- Buttons should be passed as a parameter

**Comment by yassinmoussamih** [comment]
Casati Davide
